### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by syntaxys** [joeig/dyndns-pdns#4]
Tried to install the app with recommended command `go get -u github.com/joeig/dyndns-pdns` and the result is `package github.com/joeig/dyndns-pdns: no Go files in /path/to/go/src/github.com/joeig/dyndns-pdns`. What's wrong?

Actually I don't have experience with Go but got a „Hello World!“ app running without any problems, so I guess my Go installation works well.

**Comment by joeig** [comment]
Thanks for reporting this documentation issue. I updated the `README.md` file accordingly. It should work using the full path to the command module:

```
go get -u github.com/joeig/dyndns-pdns/cmd/dyndns-pdns
```
